server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**

        - id: leave-service
          uri: lb://leave-service
          predicates:
            - Path=/leave/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
