
server:
  port: 8083
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
